RegisterNUICallback(Config.closeEvent, function(data, cb)
    SetNuiFocus(false, false)
    SendNUIMessage({ action = Config.CloseEvent })
    cb('ok')
end)

RegisterCommand(Config.CommandName, function()
    SetNuiFocus(true, true)
    SendNUIMessage({ action = Config.OpenEvent })
end)